### ISSUE TITLE
Console does not work globally

### ISSUE THREAD

**Issue by joaobrunoah** [bluejamesbond/Scribe.js#35]
Before this Scribe.js update,to 2.0, I could use my console definitions on server.js to my whole application, including imported libraries. Those definitions included created loggers, such as "debug", for example. I can't do this anymore, can I? Is that a known issue?

**Comment by guillaumewuip** [comment]
Yes, it's not a bug, but a feature :smile: 

For Scribe v1.x, we were overriding `global.console` methods. Now, we create a new console object, without overriding the old one (in order to not cause problem for libraries). By default, scribe attach the console to process.console which is shared across the whole app.

So, to use the console for your whole app, do :

```js 

//main.js

require('scribe-js')(); //by default it attach a console to `process.console`
var myLib = require('./sub-lib.js');

var console = process.console; //use process.console instead of global.console
console.log("hello world");

myLib.doSomething();
```

```js
//sub_lib.js

//you should tell your module to not use global.console
var console = process.console; //the console created in main.js is still here.

module.export = {
   doSomething : function () {
         console.tag("hi").log("using the scribe console from main in a lib");
   }
};
```

For more infos, check the wiki : https://github.com/bluejamesbond/Scribe.js/wiki/5-%C2%B7-Tips-n%27-Tricks#using-scribe-through-your-modules

Hope it's more clear :)

**Comment by joaobrunoah** [comment]
Got it! At first I thought it was weird, but it's really more organized! Thanks!
